### ISSUE TITLE
Input events in the toolbar trigger window position and size changes

### ISSUE THREAD

**Issue by jmatth** [macosui/macos_ui#317] opened 2022-11-15 16:08 UTC
**Description**

When using macOS 11 style windows, click events in the toolbar still trigger window changes even if they are located over a UI element. This includes double-clicking changing the window size, and click-and-drag moving the window. 

**Steps To Reproduce**

1. Run the example app
2. Navigate to any page in the sidebar with UI elements in the toolbar. The "Toolbar" page is a good option
3. Double click any UI element in the toolbar and the window will resize
4. With the window un-maximized, click and drag a UI element in the toolbar. The window will move with your cursor

**Expected behavior**

Input events on UI elements should take priority and not trigger window resize or move events, as in native and even most non-native applications.

**Screenshots**

Here is an example of double click triggering window resize in the example app:

https://user-images.githubusercontent.com/1316184/201949806-4bfe746f-6570-4d07-9148-2b00c12b0d71.mov

For comparison, here is the behavior of a similar element in the macOS notes application:

https://user-images.githubusercontent.com/1316184/201949986-f12991de-066b-4347-8805-18af97f2e5fc.mov

**Logs**

N/A.

**Suggestion**

The root cause seems to be that the way the runner app handles the macOS 11 style window: the titlebar is not removed but just made transparent, and therefore still receives input. Setting `self.titlebarAppearsTransparent = false` in `MainFlutterWindow` lets us see this:

<img width="912" alt="Screenshot 2022-11-15 at 09 43 11" src="https://user-images.githubusercontent.com/1316184/201961093-48b31bea-9e21-43b5-b404-30c9dd44f1b6.png">

One possible way to fix this would be to remove the titlebar entirely and handle window movement internally with a package like [bitsdojo_window](https://pub.dev/packages/bitsdojo_window). This would likely require changes to the `Toolbar` and/or `MacosScaffold` widgets to attach the required listeners.

**Related**

#316 includes these issues along with an unrelated button styling issue

**Comment by doortts** [comment] 2022-12-27 17:46
I think it is very inconvenient behavior. [GroovinChip](https://github.com/GroovinChip/macos_ui/commits?author=GroovinChip) Have you any plan about it?

**Comment by doortts** [comment] 2022-12-27 17:47
I think it is very inconvenient behavior. Have you any plan about it? @GroovinChip

**Comment by cbenhagen** [comment] 2023-02-18 18:44
Duplicate of #308

**Comment by GroovinChip** [comment] 2023-02-18 18:46
Closing as duplicate of #308, as noted.

**Closed as not planned by GroovinChip** 2023-02-18 18:46 UTC
Labels: bug
