### ISSUE TITLE
BackButton

### ISSUE THREAD

**Issue by GroovinChip** [macosui/macos_ui#97] opened 2021-05-19 01:26 UTC
<img width="194" alt="Screen Shot 2021-05-18 at 9 25 57 PM" src="https://user-images.githubusercontent.com/4250470/118743092-ad8b0c00-b81f-11eb-8a3a-ec928d7ed6f9.png">

Goes on Titlebars, I think. @lesliearkorful

**Comment by lesliearkorful** [comment] 2021-05-19 01:27
Yeah it's in the UI design kit

**Comment by GroovinChip** [comment] 2021-05-19 01:34
Our Scaffold should imply a BackButton like the Material Scaffold does

**Comment by GroovinChip** [comment] 2021-05-20 16:35
<img width="194" alt="Screen Shot 2021-05-20 at 12 35 31 PM" src="https://user-images.githubusercontent.com/4250470/119016411-e6ce9380-b967-11eb-855b-1d56ca2e1930.png">

Back button when being pressed

**Comment by GroovinChip** [comment] 2021-05-20 16:41
<img width="194" alt="Screen Shot 2021-05-20 at 12 41 12 PM" src="https://user-images.githubusercontent.com/4250470/119017163-b5a29300-b968-11eb-8d04-5c352658c54e.png">

Being pressed in light mode

**Comment by GroovinChip** [comment] 2021-05-20 16:59
First pass at this has been completed. More work to be done. Follow progress in https://github.com/GroovinChip/macos_ui/tree/back_button

**Comment by bdlukaa** [comment] 2021-05-21 00:27
I guess this is a duplicate of #85, since the backbutton is just an icon button with a function that returns to the previous screen

**Comment by GroovinChip** [comment] 2021-05-21 00:37
Nah, BackButton is a dedicated widget because it has a default action and also has a different spec

**Closed as completed** 2021-05-23 00:01 UTC
Labels: new widget
