### ISSUE TITLE
Reopen window bug

### ISSUE THREAD

**Issue by shiguanghuxian** [macosui/macos_ui#284] opened 2022-07-13 13:48 UTC
Starting from version 0.15.0, when you click x to close the window, and click the icon again to display the window, the color picker will be displayed
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/13268627/178749327-6365f3f2-6a24-4959-b6a8-80a78e3e606f.png">

**Comment by GroovinChip** [comment] 2022-07-13 14:27
Does this happen for debug builds? Release builds? Both? Was the color picker opened when the application was closed? I need more details, please.

**Comment by shiguanghuxian** [comment] 2022-07-13 16:01
> Does this happen for debug builds? Release builds? Both? Was the color picker opened when the application was closed? I need more details, please.

Both Debug and Release mode can be reproduced. After clicking on the upper left corner to close the window, the application enters the background. When you click the icon to open the application again, the color picker will open.

**Comment by GroovinChip** [comment] 2022-07-14 14:23
Is the color picker open prior to closing the app?

**Comment by shiguanghuxian** [comment] 2022-07-14 14:32
> Is the color picker open prior to closing the app?

Uncertain when closing, you can see the color picker every time you reopen the window

**Comment by GroovinChip** [comment] 2022-07-14 15:14
Yeah, I understand you see it when you reopen the app, you've mentioned that several times. Are you telling me that when you close the app you don't know if the color picker is open? Can you see it at all before you close the app?

**Comment by shiguanghuxian** [comment] 2022-07-14 23:52
> Yeah, I understand you see it when you reopen the app, you've mentioned that several times. Are you telling me that when you close the app you don't know if the color picker is open? Can you see it at all before you close the app?

Yes, I don't know whether the color picker is turned on when it is turned off. As the app is turned off, the color picker will disappear. It should be noted that clicking close will not really exit the application, but only enter the background

**Comment by GroovinChip** [comment] 2022-07-14 23:57
I see. Well, I can verify that this behavior isn't appearing in any of the mac apps I work on. But none of those apps use the color picker, so I will try to reproduce the issue and see if I can figure out what's happening.

**Comment by GroovinChip** [comment] 2022-10-04 13:31
I've been unable to reproduce this issue, so I am closing it.

**Closed as not planned by GroovinChip** 2022-10-04 13:31 UTC
Labels: bug
